import { existsSync, cpSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const EVIDENCE = join(ROOT, 'evidence');

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function copyIfExists(src, dest, label) {
  if (existsSync(src)) {
    ensureDir(dest);
    cpSync(src, dest, { recursive: true });
    console.log(`  ✓ ${label}`);
    return true;
  }
  console.log(`  - (skip) ${label} — source not found`);
  return false;
}

console.log('\nCopying test artifacts to evidence/\n');

const copied = [];

if (
  copyIfExists(
    join(ROOT, 'playwright-report'),
    join(EVIDENCE, 'reports', 'playwright'),
    'Playwright HTML report',
  )
) {
  copied.push('`evidence/reports/playwright/index.html`');
}

if (
  copyIfExists(
    join(ROOT, 'allure-results'),
    join(EVIDENCE, 'reports', 'allure-results'),
    'Allure results',
  )
) {
  copied.push('`evidence/reports/allure-results/` (run `npm run allure:serve` to view)');
}

if (
  copyIfExists(
    join(ROOT, 'test-results'),
    join(EVIDENCE, 'screenshots', 'test-results'),
    'Test result artifacts',
  )
) {
  copied.push('`evidence/screenshots/test-results/`');
}

// Write run manifest
const now = new Date();
const timestamp = now.toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
const dateLabel = now.toISOString().substring(0, 10);

const manifest = [
  `# Last Test Run`,
  ``,
  `**Date:** ${timestamp}`,
  `**Target:** https://demo.opencart.com`,
  `**Suite:** quality:full (Playwright + Cypress)`,
  ``,
  `## Artifacts`,
  ``,
  copied.length > 0
    ? copied.map((line) => `- ${line}`).join('\n')
    : '_No artifacts found. Run `npm run quality:full` first._',
  ``,
  `## Open Reports`,
  ``,
  `\`\`\`bash`,
  `npm run test:pw:report   # Playwright HTML`,
  `npm run allure:serve     # Allure interactive`,
  `\`\`\``,
  ``,
  `---`,
  `_Generated by \`npm run reports\` on ${dateLabel}_`,
].join('\n');

ensureDir(EVIDENCE);
writeFileSync(join(EVIDENCE, 'LAST-RUN.md'), manifest, 'utf8');
console.log(`  ✓ Run manifest → evidence/LAST-RUN.md`);

console.log('\n✓ Done.\n');
console.log('  Open Playwright report:  npm run test:pw:report');
console.log('  Open Allure report:      npm run allure:serve\n');
